# Unique project key in SonarQube
sonar.projectKey=falcone-cipp

# Source directories
sonar.sources=src

# Exclude unnecessary files/folders from analysis
sonar.exclusions=**/node_modules/**, **/tests/**, .circleci/config.yml

# Optional: language-specific properties
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
