sonar.projectKey=Falcone-CIPP-International-Payments-Portal2020
sonar.host.url=http://localhost:9000
sonar.login=sqp_4a6995e45f177723af078c71892446b5178089fe
sonar.sources=.
sonar.exclusions=node_modules/**
sonar.language=js
sonar.sourceEncoding=UTF-8
